spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:23145/demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&autoReconnect=true&maxReconnects=10&failOverReadOnly=false
    username: root
    #native image can't user system env ${password}
    password: 135246xyx
    hikari:
      connection-timeout: 500000
      max-lifetime: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  cache:
    type: simple
    cache-names: token_jwt