spring:
  datasource:
    url: jdbc:mysql://mysql:3306/demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&autoReconnect=true&maxReconnects=10&failOverReadOnly=false
    username: root
    password: 135246xyx
    hikari:
      connection-timeout: 500000
      max-lifetime: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
  cache:
    type: simple
    cache-names: token_jwt